/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTechnicianRouteImport } from './routes/_authenticated/technician'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin.appointments'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminTechniciansRouteImport } from './routes/_authenticated/admin.technicians'
import { Route as AuthenticatedTechnicianIndexRouteImport } from './routes/_authenticated/technician.index'
import { Route as AuthenticatedTechnicianDashboardRouteImport } from './routes/_authenticated/technician.dashboard'
import { Route as AuthenticatedTechnicianProfileRouteImport } from './routes/_authenticated/technician.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTechnicianRoute = AuthenticatedTechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTechniciansRoute =
  AuthenticatedAdminTechniciansRouteImport.update({
    id: '/technicians',
    path: '/technicians',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTechnicianIndexRoute =
  AuthenticatedTechnicianIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTechnicianRoute,
  } as any)
const AuthenticatedTechnicianDashboardRoute =
  AuthenticatedTechnicianDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedTechnicianRoute,
  } as any)
const AuthenticatedTechnicianProfileRoute =
  AuthenticatedTechnicianProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTechnicianRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/technician': typeof AuthenticatedTechnicianRouteWithChildren
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/technicians': typeof AuthenticatedAdminTechniciansRoute
  '/technician/dashboard': typeof AuthenticatedTechnicianDashboardRoute
  '/technician/profile': typeof AuthenticatedTechnicianProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/technician/': typeof AuthenticatedTechnicianIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/technicians': typeof AuthenticatedAdminTechniciansRoute
  '/technician/dashboard': typeof AuthenticatedTechnicianDashboardRoute
  '/technician/profile': typeof AuthenticatedTechnicianProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/technician': typeof AuthenticatedTechnicianIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/technician': typeof AuthenticatedTechnicianRouteWithChildren
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/technicians': typeof AuthenticatedAdminTechniciansRoute
  '/_authenticated/technician/dashboard': typeof AuthenticatedTechnicianDashboardRoute
  '/_authenticated/technician/profile': typeof AuthenticatedTechnicianProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/technician/': typeof AuthenticatedTechnicianIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/dashboard'
    | '/technician'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/technicians'
    | '/technician/dashboard'
    | '/technician/profile'
    | '/admin/'
    | '/technician/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/requests'
    | '/admin/services'
    | '/admin/technicians'
    | '/technician/dashboard'
    | '/technician/profile'
    | '/admin'
    | '/technician'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/technician'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/technicians'
    | '/_authenticated/technician/dashboard'
    | '/_authenticated/technician/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/technician/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technician': {
      id: '/_authenticated/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof AuthenticatedTechnicianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/technicians': {
      id: '/_authenticated/admin/technicians'
      path: '/technicians'
      fullPath: '/admin/technicians'
      preLoaderRoute: typeof AuthenticatedAdminTechniciansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/technician/': {
      id: '/_authenticated/technician/'
      path: '/'
      fullPath: '/technician/'
      preLoaderRoute: typeof AuthenticatedTechnicianIndexRouteImport
      parentRoute: typeof AuthenticatedTechnicianRoute
    }
    '/_authenticated/technician/dashboard': {
      id: '/_authenticated/technician/dashboard'
      path: '/dashboard'
      fullPath: '/technician/dashboard'
      preLoaderRoute: typeof AuthenticatedTechnicianDashboardRouteImport
      parentRoute: typeof AuthenticatedTechnicianRoute
    }
    '/_authenticated/technician/profile': {
      id: '/_authenticated/technician/profile'
      path: '/profile'
      fullPath: '/technician/profile'
      preLoaderRoute: typeof AuthenticatedTechnicianProfileRouteImport
      parentRoute: typeof AuthenticatedTechnicianRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminTechniciansRoute: typeof AuthenticatedAdminTechniciansRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminTechniciansRoute: AuthenticatedAdminTechniciansRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedTechnicianRouteChildren {
  AuthenticatedTechnicianDashboardRoute: typeof AuthenticatedTechnicianDashboardRoute
  AuthenticatedTechnicianProfileRoute: typeof AuthenticatedTechnicianProfileRoute
  AuthenticatedTechnicianIndexRoute: typeof AuthenticatedTechnicianIndexRoute
}

const AuthenticatedTechnicianRouteChildren: AuthenticatedTechnicianRouteChildren =
  {
    AuthenticatedTechnicianDashboardRoute:
      AuthenticatedTechnicianDashboardRoute,
    AuthenticatedTechnicianProfileRoute: AuthenticatedTechnicianProfileRoute,
    AuthenticatedTechnicianIndexRoute: AuthenticatedTechnicianIndexRoute,
  }

const AuthenticatedTechnicianRouteWithChildren =
  AuthenticatedTechnicianRoute._addFileChildren(
    AuthenticatedTechnicianRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTechnicianRoute: typeof AuthenticatedTechnicianRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTechnicianRoute: AuthenticatedTechnicianRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
